### ISSUE TITLE
[JOSS Review] 

### ISSUE THREAD

**Issue by kellertuer** [ranocha/SummationByPartsOperators.jl#108]
# Review on the JOSS paper on SummationByPartsOperators.jl

The submitted manuscript is about a Julia package and in general well written.
While the text is easy to read, I am missing a few points from the JOSS Guidelines which should be covered in the paper, I think. I will continuously number my points, just for easier reference, though the later remarks are easier to solve.

The package itself
- has a proper license file
- has substantial scholarly effort and is used in academic papers of the submitting author and his coauthors
- has guidelines how to contribute (a `CONTRIBUTE.md`)
- has a reasonable test coverage of 92%

## Remarks
1. An installation instruction is missing. This can be easily resolved when taking into account the second point
2. I am missing a simple example, i.e. how to get started, solve an easy task with the package. This could also start with how to install the package. It would be nice to have a little more theory with such an example than just the code lines, e.g. as they are given in the “Basic Example” section in the `Readme.md`. Maybe it is not reasonable to put code into the paper (though the examples from the readme also have to be copied line-by-line currently), but maybe then a section on the mathematical background would be neat? On the other hand for example [here](https://joss.theoj.org/papers/10.21105/joss.02520) also some code was included, so I think that would be neat, too.
3. I noticed that the Summary/Abstract is a one-to-one copy of the first paragraph from the package readme. I am new to reviewing for JOSS, so I am not sure whether that is usual. 
4. Concerning related sopftware I have two remarks
  * It does not get clear to what extend there is an overlap of the current package to the mentioned ones. For example it sounds a little bit like the current package can be used to solve _all_ problems from the mentioned packages? A little more detail on the relations would be neat
  * While for the first related software both the title/link to the software are mentioned as well as a reference, oáll others are just mentioned with a reference. Could these maybe be extended to also cover software package names and links to the repositories?

## Minor Remarks
5. line 19: The word “resulting” seems to be mispaceed. Just the development of software will most probably not lead to disjoint communities. Maybe you meant that disjoint communities yuield different implementations and what is missing is a joint approach, also because the disjoint communities use different vocabulary?
6. line 32/33: You calim that the package is “reasonably fast”, but this is nowhere supported by a benchmark, comparison or reference. Where does this claim originate from? Sure there is a Benchmark section in the documentation, but I am missing a comparison to other approaches/packages for such a claim. This might also be, because I am – concerning these numerics – not an expert on performance. It would be nice to still justify this claim.
7. line 35: The claim that the software was used in graduate courses is also without reference/example nor what the benefits of using it were.
8. line 55: the term “both” is followed by an enumeration of three terms (with the correct use of a comma before the “and”), so “both” is a wrong reference for this
9. Conerning the API, the available functions are currently listed alphabetically on one page. Might it be a reasonable point to organise them a little more by topic?
 
## Typographical Remarks

10. line 30: Should the package name maybe be set as code, i.e. not SummationByParts.jl but `SummationByParts.jl`?
11. line 43: The word “basically” can maybe be left out?
12. lines 49/50: the words “artificial dissipation” is used in line 49 and again directly in the first example line 50, so this is a repetition. Can this maybe be avoided?
13. the example from the readme, especially the command `D = periodic_derivative_operator(derivative_order=1, accuracy_order=2, xmin=0.0, xmax=2.0, N=20)` should return a `show` which is a constructor instead of an explaining text and a reference in REPL. I looked a while for a reference for this claim and can not find it, but I am used to `show` methods to print a constructor that recreates the type.
14.   Also more like two short techical remarks: The “Edit on GitHub” links from the Documentation for Contributing and License do not work. I think this might be due to the reason that they are included atuomatically from the main repository (which is of course very good to avoid duplication). Can you maybe check how this might be avoidable?

While this is a little longish, let me summarise that in general it is of course still a good submission and should be accepted after these points are addressed :)

**Comment by ranocha** [comment]
Thank you very much for your prompt and thorough review, @kellertuer! Please find below some comments on the issues raised above. I created PR #109 to resolve your remaining comments. I would be happy if you could review #109 and discuss any additional/remaining issues ehre or in that PR. I hope we can resolve this issue soon.

- > An installation instruction is missing. This can be easily resolved when taking into account the second point

  As far as I have understood the [review criteria of JOSS](https://joss.readthedocs.io/en/latest/review_criteria.html#installation-instructions), an installation instruction should be included in the documentation of the software, not in the paper itself. I expect the reason for this is that the installation procedure might change while the software evolves while the paper is static after publication.
  Nevertheless, I added a sentence mentioning that SummationByPartsOperators.jl is a registered Julia package to the paper. If you think that this is insufficient and a more detailed Julia code example should be included in the paper, please tell me and I will be happy to prepare such an example.
- > I am missing a simple example, i.e. how to get started, solve an easy task with the package. This could also start with how to install the package. It would be nice to have a little more theory with such an example than just the code lines, e.g. as they are given in the “Basic Example” section in the Readme.md. Maybe it is not reasonable to put code into the paper (though the examples from the readme also have to be copied line-by-line currently), but maybe then a section on the mathematical background would be neat? On the other hand for example [here](https://joss.theoj.org/papers/10.21105/joss.02520) also some code was included, so I think that would be neat, too.

  I tried to follow the [JOSS guideline for authors](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain), stating that
  > software documentation such as API (Application Programming Interface) functionality should not be in the paper and instead should be outlined in the software documentation

  Thus, it appears inappropriate to include such an example in the paper itself. I guess the reasoning is that the software will evolve but the paper is static. Thus, it should be avoided to document an API that might be out of date in the future.
- > I noticed that the Summary/Abstract is a one-to-one copy of the first paragraph from the package readme. I am new to reviewing for JOSS, so I am not sure whether that is usual.

  Given that JOSS is an open access software journal and the paper [should contain](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain)

  > a summary describing the high-level functionality and purpose of the software

  this paragraph appeared to do the job. If you think I should modify it, please let me know.
- > line 30: Should the package name maybe be set as code, i.e. not SummationByParts.jl but `SummationByParts.jl`?

  I don't think so since it is the name of a package, not some real (Julia) code. The example [you have linked above](https://joss.theoj.org/papers/10.21105/joss.02520) does also not use monospaced font for the package name.
- > the example from the readme, especially the command `D = periodic_derivative_operator(derivative_order=1, accuracy_order=2, xmin=0.0, xmax=2.0, N=20)` should return a show which is a constructor instead of an explaining text and a reference in REPL. I looked a while for a reference for this claim and can not find it, but I am used to show methods to print a constructor that recreates the type.

  I would be happy to see a reference for this request. In my experience, such a behavior is not generic in Julia. For example, the SciML ecosystem follows the approach to provide high-level information about objects instead of (used also by SummationByPartsOperators.jl):
  ```julia
  julia> using OrdinaryDiffEq

  julia> ode = ODEProblem((u, p, t) -> u, 1.0, (0.0, 1.0))
  ODEProblem with uType Float64 and tType Float64. In-place: false
  timespan: (0.0, 1.0)
  u0: 1.0

  julia> sol = solve(ode, Tsit5())
  retcode: Success
  Interpolation: specialized 4th order "free" interpolation
  t: 5-element Vector{Float64}:
  0.0
  0.10001999200479662
  0.3480203186480749
  0.6830525653177172
  1.0
  u: 5-element Vector{Float64}:
  1.0
  1.105193012902056
  1.4162610240705922
  1.9799122739515003
  2.718281708773342
  ```
  In addtion, other basic pacakges do also not print something that can be used directly as constructor, e.g.
  ```julia
  julia> x = SVector(1.0, 2.0)
  2-element SVector{2, Float64} with indices SOneTo(2):
  1.0
  2.0
  ```
  Of course, something like `x = range(0.0, 1.0, length=51); plot(x, sinpi.(x))` will also not print a constructor-like information.
- > Also more like two short techical remarks: The “Edit on GitHub” links from the Documentation for Contributing and License do not work. I think this might be due to the reason that they are included atuomatically from the main repository (which is of course very good to avoid duplication). Can you maybe check how this might be avoidable?

  I couldn't find a way to do so and [filed an issue](https://github.com/JuliaDocs/Documenter.jl/issues/1650).
- > Conerning the API, the available functions are currently listed alphabetically on one page. Might it be a reasonable point to organise them a little more by topic?

  Such an API documentation sorted by topic is basically provided in the section [Introduction](https://ranocha.de/SummationByPartsOperators.jl/stable/introduction/) in the docs. Additional example-guided API documentation is provided in form of tutorials such as [on the linear advection equation](https://ranocha.de/SummationByPartsOperators.jl/stable/tutorials/constant_linear_advection/).

**Comment by kellertuer** [comment]
For the first point I am fine with mentioning that it is a registered package; that solves point 1.

Concerning 2) For the example, we seem to have different views. Let me carefully elaborate on mine.
I think an easy to start example would be helpful to a reader of the paper. It does not have to be the most elaborate one or the most complicated – mainly to introduce the main mathematical background and directly illustrate how that maps to some code. Note that some have even [quite long](https://joss.theoj.org/papers/10.21105/joss.02520) examples – where one might argue that “printing” so much code might not be what one wants.

The argument with the API seems to me bad in both views that one might have to that: (1) if your API does changes so much as you claim, the package might not be as mature as it should be for a paper? (2) An example could also use only those (basic/main) API parts that are mature enough so the example would also work in the (far) future. Finally the example could mention the version of the package to be reproducible for sure.

Concerning 3) I am sure content wise it summarises the package well – I am not sure whether it is meant to be that you copy that fro somewhere (in harsh words one could think about self-plagiarism?)

Concerning 4) a) seems to be resolved and b) I addressed in #109 with a small comment

Points 5--13 are addressed in #109 I think; and cool that you fixed 14.

So only 2&3 are left to discuss here.

**Comment by kellertuer** [comment]
A I forgot to talk about the show method – thanks for the details, then you show method might also be fine. As I said I could not find the reference for the show methods we do, but maybe that also depends on the simplicity of the type (struct) at hand; usually our structs are quite plain ones.

**Comment by ranocha** [comment]
Concerning 2): I added such a basic example in c663429 in #109.

**Comment by ranocha** [comment]
Concerning 3): I updated the summary of the package in the README.md.

**Comment by kellertuer** [comment]
Cool. Then up to the minor remarks over in #109 we are done and I just have to check the final PDF again (and my checkpoints I ddi not check over in the JOSS review issue), but this Issue can be already closed I think.
